/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cn.itcreator.android.reader;

public final class R {
    public static final class array {
        public static final int audioEnds=0x7f040004;
        public static final int background=0x7f040002;
        public static final int colors=0x7f040000;
        public static final int fontsize=0x7f040001;
        public static final int imageEnds=0x7f040003;
        public static final int packageEnds=0x7f040005;
        public static final int textEnds=0x7f040006;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int addbookmark=0x7f020000;
        public static final int applegray=0x7f020001;
        public static final int audio=0x7f020002;
        public static final int circscreen=0x7f020003;
        public static final int close=0x7f020004;
        public static final int delete=0x7f020005;
        public static final int fail=0x7f020006;
        public static final int folder32=0x7f020007;
        public static final int goroot=0x7f020008;
        public static final int icon=0x7f020009;
        public static final int image32=0x7f02000a;
        public static final int packed=0x7f02000b;
        public static final int setbackgroud=0x7f02000c;
        public static final int setfont=0x7f02000d;
        public static final int success=0x7f02000e;
        public static final int text32=0x7f02000f;
        public static final int uponelevel=0x7f020010;
        public static final int viewbookmark=0x7f020011;
        public static final int webtext=0x7f020012;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f060005;
        public static final int TableLayout01=0x7f060000;
        public static final int TableRow01=0x7f060007;
        public static final int bmcancel=0x7f060004;
        public static final int bmet=0x7f060002;
        public static final int bmsure=0x7f060003;
        public static final int bookmarklistview=0x7f060006;
        public static final int cancelbm=0x7f06000a;
        public static final int deletebm=0x7f060008;
        public static final int fontcolorspinner=0x7f06000c;
        public static final int fontsizespinner=0x7f06000b;
        public static final int gotoreader=0x7f06000e;
        public static final int scrollView=0x7f06000f;
        public static final int skipbm=0x7f060009;
        public static final int textContent=0x7f060011;
        public static final int textLayout=0x7f060010;
        public static final int tre=0x7f060001;
        public static final int viewfont=0x7f06000d;
    }
    public static final class layout {
        public static final int bookmark_dialog=0x7f030000;
        public static final int bookmarklist=0x7f030001;
        public static final int file_row=0x7f030002;
        public static final int fontset=0x7f030003;
        public static final int reader=0x7f030004;
    }
    public static final class string {
        public static final int about=0x7f050025;
        public static final int aboutcoolreader=0x7f050026;
        public static final int ad=0x7f050006;
        public static final int app_name=0x7f050000;
        public static final int back=0x7f05001e;
        public static final int bookmarklist=0x7f05000b;
        public static final int cancel=0x7f050020;
        public static final int changebg=0x7f05000f;
        public static final int changecolor=0x7f050023;
        public static final int changefont=0x7f05000e;
        public static final int changefontsize=0x7f050024;
        public static final int circumgyrate=0x7f050010;
        public static final int current_dir=0x7f05000c;
        public static final int delete=0x7f050022;
        public static final int deletebookmark=0x7f050012;
        public static final int deletefail=0x7f05001a;
        public static final int deletefile=0x7f05001c;
        public static final int deleteresult=0x7f050018;
        public static final int deletesuccess=0x7f050019;
        public static final int dirname_app_name=0x7f050001;
        public static final int dirnameinput_cmd_return=0x7f050003;
        public static final int dirnameinput_hint=0x7f050004;
        public static final int exit=0x7f05001d;
        public static final int filenotfound=0x7f050028;
        public static final int gomark=0x7f050021;
        public static final int inputbmname=0x7f050014;
        public static final int menu_new_folder=0x7f050002;
        public static final int mybackground=0x7f050007;
        public static final int ourintroduce=0x7f050027;
        public static final int savebookmark=0x7f050011;
        public static final int savefail=0x7f050017;
        public static final int saveresult=0x7f050015;
        public static final int savesuccess=0x7f050016;
        public static final int selectfontcolor=0x7f050009;
        public static final int selectfontsize=0x7f050008;
        public static final int setting=0x7f05000d;
        public static final int sure=0x7f05001f;
        public static final int suredelete=0x7f05001b;
        public static final int up_one_level=0x7f050005;
        public static final int viewbookmark=0x7f050013;
        public static final int viewfont=0x7f05000a;
    }
}
